### ISSUE TITLE
What happens once the exception is caught?

### ISSUE THREAD

**Issue by chichilatte** [distriqt/ANE-Exceptions#11]
Sorry if I'm being a dope, but once the ANE catches an exception, what happens then? Does it rethrow the error so the app crashes, or does it just close the app?

It'd be really great for play store rankings if normally-uncaught exceptions could be handled without crashing the app (if that is even possible).

Thanks in advance for yr answer @marchbold, super appreciated since this is a free ANE 👌

**Comment by marchbold** [comment]
Hi,

The application will still terminate, however you'll be able to check on the next launch whether the application crashed due to an exception:

```as3
if (Exceptions.service.hasPendingException())
{
	var report:ExceptionReport = Exceptions.service.getPendingException();
	trace( "date: "+    new Date(report.timestamp).toLocaleString() );
	trace( "name: "+    report.name );
	trace( "reason: "+  report.reason );
	trace( "report: "+  report.report );
}
```

It's not really possible to continue an app when an unhandled exception occurs. Unless the exception is handled in the place it occurred these are normally terminal meaning whatever thread caused the exception cannot continue.

Hope that clears it up?

**Comment by chichilatte** [comment]
Ah gotcha, I thought maybe the exception handler could do some sort of clean exit, like `System.exit(0)` so crashes aren't reported to Google. But thinking about it, it's incredibly useful to see crash contexts in the Google Console, even if it hurts ranking. I'll stop nattering now, thanks for yr time 👍
